package com.example.triqx.service.email

import android.content.Intent
import com.example.triqx.data.local.EmailAccountEntity

/**
 * Unified interface contract for email providers (Gmail, Microsoft Outlook).
 * Encapsulates authentication, token refresh lifecycle, and reply dispatching.
 */
interface EmailService {
    /**
     * Provider identifier (GMAIL, OUTLOOK).
     */
    val provider: EmailProvider

    /**
     * Android package names associated with this provider (e.g. com.google.android.gm).
     */
    val supportedPackages: List<String> get() = provider.supportedPackages

    /**
     * Checks if this provider handles notifications from the given app package.
     */
    fun canHandle(packageName: String): Boolean {
        return supportedPackages.any { pkg ->
            packageName.contains(pkg, ignoreCase = true) || pkg.contains(packageName, ignoreCase = true)
        }
    }

    /**
     * Builds the Intent to initiate user authorization (e.g. Google Sign-In or Microsoft OAuth2).
     */
    suspend fun createAuthorizationIntent(): Intent

    /**
     * Processes the result Intent from the authorization activity/custom tab,
     * fetches access tokens and user profile, and persists the account into storage.
     */
    suspend fun handleAuthorizationResult(resultIntent: Intent): Result<EmailAccountEntity>

    /**
     * Obtains a valid Bearer OAuth access token for the given account,
     * refreshing transparently if needed.
     */
    suspend fun getValidAccessToken(account: EmailAccountEntity): String?

    /**
     * Resolves parent email thread/conversation metadata and sends the reply.
     *
     * @param account User's connected account from which the reply is sent
     * @param recipientEmail Clean email address of the recipient
     * @param subject Original subject line or thread title
     * @param replyText Reply body generated by the AI assistant
     * @return Result with sent message/conversation ID, or failure
     */
    suspend fun sendReply(
        account: EmailAccountEntity,
        recipientEmail: String,
        subject: String?,
        replyText: String
    ): Result<String>

    /**
     * Disconnects the specific account from this provider.
     */
    suspend fun disconnectAccount(emailAddress: String)

    /**
     * Disconnects all accounts associated with this provider.
     */
    suspend fun disconnectAll()
}
